Repository microsoft/mu_rust_helpers, pull requests merged in 2024-09, with the labels that each got.

#13 Add GUID helpers
  Cargo.toml
  guid/Cargo.toml
  guid/src/guid.rs
  src/lib.rs
Labels: impact:breaking-change, impact:non-functional, impact:testing, type:documentation

#16 Add a test for free_pages()
  boot_services/src/boot_services.rs
Labels: impact:non-functional, impact:testing

#17 boot_services.rs: Add a test for allocate pool
  boot_services/src/boot_services.rs
Labels: impact:non-functional, impact:testing

#18 Add a test for free pool
  boot_services/src/boot_services.rs
Labels: impact:non-functional, impact:testing

#19 Documentation improvements for boot_services
  boot_services/src/boot_services.rs
Labels: impact:non-functional, type:documentation

#22 Added Variable Serivce Wrappers for Runtime Services
  Cargo.toml
  runtime_services/Cargo.toml
  runtime_services/src/runtime_services.rs
  runtime_services/src/variable_services.rs
  src/lib.rs
Labels: impact:testing, impact:security, type:documentation

#28 Cargo.toml: Update version to 1.0.1
  Cargo.toml
Labels: impact:non-functional, semver:patch

#24 [Rebase & FF] Add a test for get memory map wrapper
  boot_services/src/allocation.rs
  boot_services/src/boot_services.rs
Labels: impact:non-functional, impact:testing
